---
################################################################################
# Any local customizations should be placed inside the .kitchen.local.yml, which
# will not be checked in or overwritten. You may also use ~/.kitchen/config.yml
# or environment variables like VAGRANT_DEFAULT_PROVIDER. Anything in those will
# take precedence over anything set in `.kitchen.yml`.
################################################################################
driver:
  name: vagrant # provide a default test-kitchen driver, vagrant

provisioner:
  name: chef_zero
  nodes_path: 'test/fixtures/nodes'
  data_bags_path: 'test/fixtures/data_bags'
  environments_path: 'test/fixtures/environments'
  client_rb:
    environment: _default
  attributes:
    java:
      jdk_version: '7'

platforms:
  - name: ubuntu-14.04
    run_list:
    - recipe[apt]
    - recipe[curl]
  - name: ubuntu-12.04
    run_list:
    - recipe[apt]
    - recipe[curl]
  - name: centos-6.7
    run_list:
    - recipe[yum]
    - recipe[curl]
    - recipe[elasticsearch_test::fix_nss] # see recipe header

suites:
  - name: package # install from package
    require_chef_omnibus: 12.6.0
    run_list:
      - recipe[java]
      - recipe[elasticsearch_test::default_with_plugins]
    attributes:
      elasticsearch:
        install_type: package

  - name: tarball # install by tarball
    require_chef_omnibus: 12.6.0
    run_list:
      - recipe[java]
      - recipe[elasticsearch_test::default_with_plugins]
    attributes:
      elasticsearch:
        install_type: tarball

  - name: override_package # the override-everything use case
    driver_config:
      require_chef_omnibus: 12.6.0
    run_list:
      - recipe[java]
      - recipe[elasticsearch_test::package]

  - name: override_tarball # the override-everything use case
    driver_config:
      require_chef_omnibus: 12.6.0
    run_list:
      - recipe[java]
      - recipe[elasticsearch_test::tarball]

  - name: chef-12.5.1
    driver_config:
      require_chef_omnibus: 12.5.1
    includes:
      - ubuntu-14.04
    run_list:
      - recipe[java]
      - recipe[elasticsearch_test::default_with_plugins]

  - name: chef-12.4.3
    driver_config:
      require_chef_omnibus: 12.4.3
    includes:
      - ubuntu-14.04
    run_list:
      - recipe[java]
      - recipe[elasticsearch_test::default_with_plugins]

  - name: chef-12.3.0
    driver_config:
      require_chef_omnibus: 12.3.0
    includes:
      - ubuntu-14.04
    run_list:
      - recipe[java]
      - recipe[elasticsearch_test::default_with_plugins]

  - name: chef-12.2.1
    driver_config:
      require_chef_omnibus: 12.2.1
    includes:
      - ubuntu-14.04
    run_list:
      - recipe[java]
      - recipe[elasticsearch_test::default_with_plugins]

  - name: chef-12.1.2
    driver_config:
      require_chef_omnibus: 12.1.2
    includes:
      - ubuntu-14.04
    run_list:
      - recipe[java]
      - recipe[elasticsearch_test::default_with_plugins]

  - name: shieldwatcher # install licensed plugins for testing
    require_chef_omnibus: true
    run_list:
      - recipe[java]
      - recipe[elasticsearch_test::shieldwatcher]
    attributes:
      elasticsearch:
        install_type: package
