name             'elasticsearch'
maintainer       'Sous Chefs'
maintainer_email 'help@sous-chefs.org'
license          'Apache-2.0'
description      'Installs and configures Elasticsearch'
version          '6.0.1'
issues_url       'https://github.com/sous-chefs/elasticsearch/issues'
source_url       'https://github.com/sous-chefs/elasticsearch'
chef_version     '>= 16.0'

supports         'almalinux', '>= 8.0'
supports         'amazon', '>= 2023.0'
supports         'centos_stream', '>= 9.0'
supports         'debian', '>= 12.0'
supports         'fedora'
supports         'opensuseleap', '>= 15.0'
supports         'oracle', '>= 8.0'
supports         'redhat', '>= 8.0'
supports         'rocky', '>= 8.0'
supports         'ubuntu', '>= 22.04'

depends          'ark'
