name             'elasticsearch'
maintainer       'Sous Chefs'
maintainer_email 'help@sous-chefs.org'
license          'Apache-2.0'
description      'Installs and configures Elasticsearch'
version          '5.1.14'
issues_url       'https://github.com/sous-chefs/elasticsearch/issues'
source_url       'https://github.com/sous-chefs/elasticsearch'
chef_version     '>= 15.3'

supports         'amazon'
supports         'centos'
supports         'debian'
supports         'fedora'
supports         'redhat'
supports         'ubuntu'

depends          'ark'
