###
# This is the place to override the elasticsearch cookbook's default attributes.
#
# Do not edit THIS file directly. Instead, create
# "elasticsearch/attributes/customize.rb" in your cookbook repository and
# put the overrides in YOUR customize.rb file.
###

# The following shows how to override the Elasticsearch version and clustername settings:
#
#normal[:elasticsearch][:version] = '1.1.0'
#normal[:elasticsearch][:cluster][:name] = 'my-cluster'
